from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Iterable, List, Optional, Sequence, Tuple

import cv2
import numpy as np
import torch


Point = Tuple[int, int]
DEFAULT_WEIGHTS_PATH = Path("assets/weights/csrnet_shanghaitechA.pth")


def _resolve_device(device: str) -> torch.device:
    d = str(device or "cuda").strip().lower()
    if d in ("auto", ""):
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if d == "cuda" and not torch.cuda.is_available():
        return torch.device("cpu")
    return torch.device(d)


def _load_csrnet_class(project_root: Path):
    csrnet_root = project_root / "third_party" / "csrnet"
    model_file = csrnet_root / "model.py"
    if not model_file.exists():
        raise FileNotFoundError(
            f"CSRNet source not found at {model_file}. "
            "Please add the third-party module at third_party/csrnet."
        )

    # model.py imports sibling utils.py via absolute import name "utils".
    if str(csrnet_root) not in sys.path:
        sys.path.insert(0, str(csrnet_root))

    spec = importlib.util.spec_from_file_location("third_party_csrnet_model", model_file)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Failed to load CSRNet model module from {model_file}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    if not hasattr(mod, "CSRNet"):
        raise RuntimeError("CSRNet class not found in third_party/csrnet/model.py")
    return mod.CSRNet


def _to_tensor(frame_bgr: np.ndarray) -> torch.Tensor:
    rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0
    tensor = torch.from_numpy(rgb).permute(2, 0, 1).contiguous()  # [3,H,W]
    mean = torch.tensor([0.485, 0.456, 0.406], dtype=tensor.dtype).view(3, 1, 1)
    std = torch.tensor([0.229, 0.224, 0.225], dtype=tensor.dtype).view(3, 1, 1)
    tensor = (tensor - mean) / std
    return tensor.unsqueeze(0)  # [1,3,H,W]


def _polygon_mask(shape_hw: Tuple[int, int], polygon: Sequence[Point]) -> np.ndarray:
    h, w = shape_hw
    mask = np.zeros((h, w), dtype=np.uint8)
    pts = np.asarray(polygon, dtype=np.int32)
    if pts.ndim != 2 or pts.shape[1] != 2 or pts.shape[0] < 3:
        raise ValueError("roi_polygon must be a list of at least 3 (x,y) points")
    cv2.fillPoly(mask, [pts], 1)
    return mask


class CSRNetCounter:
    """
    CSRNet wrapper for OpenCV BGR frames.

    - predict_density(frame_bgr) returns density map as np.ndarray [H', W'].
      For CSRNet this is typically 1/8 of input resolution due to frontend pooling.
    - predict_count(frame_bgr, roi_polygon) sums density over full map or ROI.
    """

    def __init__(self, weights_path: str, device: str = "cuda"):
        self.project_root = Path(__file__).resolve().parents[1]
        self.device = _resolve_device(device)
        self.weights_path = Path(weights_path)
        if not self.weights_path.is_absolute():
            self.weights_path = (self.project_root / self.weights_path).resolve()

        if not self.weights_path.exists():
            raise FileNotFoundError(
                f"CSRNet weights not found: {self.weights_path}\n"
                f"Place a trained checkpoint at {self.project_root / DEFAULT_WEIGHTS_PATH}, "
                "or provide --weights pointing to a .pth/.pth.tar generated by CSRNet training."
            )

        CSRNet = _load_csrnet_class(self.project_root)
        self.model = CSRNet(load_weights=True)
        self.model.to(self.device)
        self.model.eval()
        self._load_weights(self.weights_path)

    def _load_weights(self, path: Path) -> None:
        checkpoint = torch.load(str(path), map_location=self.device)
        if isinstance(checkpoint, dict) and "state_dict" in checkpoint:
            state = checkpoint["state_dict"]
        else:
            state = checkpoint
        if not isinstance(state, dict):
            raise RuntimeError(f"Invalid checkpoint format at {path}")

        cleaned = {}
        for k, v in state.items():
            name = str(k)
            if name.startswith("module."):
                name = name[len("module.") :]
            cleaned[name] = v
        missing, unexpected = self.model.load_state_dict(cleaned, strict=False)
        if missing:
            print(f"[CSRNetCounter] Warning: missing keys ({len(missing)}), first: {missing[:5]}")
        if unexpected:
            print(f"[CSRNetCounter] Warning: unexpected keys ({len(unexpected)}), first: {unexpected[:5]}")

    def predict_density(self, frame_bgr: np.ndarray) -> np.ndarray:
        if frame_bgr is None or frame_bgr.ndim != 3 or frame_bgr.shape[2] != 3:
            raise ValueError("frame_bgr must be a BGR image np.ndarray [H,W,3]")
        x = _to_tensor(frame_bgr).to(self.device)
        with torch.no_grad():
            y = self.model(x)
        density = y.squeeze(0).squeeze(0).detach().cpu().numpy().astype(np.float32)
        return density

    def predict_count(
        self,
        frame_bgr: np.ndarray,
        roi_polygon: Optional[List[Tuple[int, int]]] = None,
    ) -> float:
        density = self.predict_density(frame_bgr)
        if roi_polygon is None:
            return float(density.sum())

        in_h, in_w = frame_bgr.shape[:2]
        d_h, d_w = density.shape[:2]
        sx = float(d_w) / float(max(in_w, 1))
        sy = float(d_h) / float(max(in_h, 1))
        scaled_poly = [(int(round(x * sx)), int(round(y * sy))) for x, y in roi_polygon]
        mask = _polygon_mask((d_h, d_w), scaled_poly)
        return float((density * mask.astype(np.float32)).sum())

    def predict_count_from_density(
        self,
        density_map: np.ndarray,
        frame_shape_hw: Tuple[int, int],
        roi_polygon: Optional[List[Tuple[int, int]]] = None,
    ) -> float:
        if roi_polygon is None:
            return float(density_map.sum())
        in_h, in_w = frame_shape_hw
        d_h, d_w = density_map.shape[:2]
        sx = float(d_w) / float(max(in_w, 1))
        sy = float(d_h) / float(max(in_h, 1))
        scaled_poly = [(int(round(x * sx)), int(round(y * sy))) for x, y in roi_polygon]
        mask = _polygon_mask((d_h, d_w), scaled_poly)
        return float((density_map * mask.astype(np.float32)).sum())


def parse_roi(roi_text: str) -> List[Point]:
    text = str(roi_text or "").strip()
    if not text:
        return []
    out: List[Point] = []
    for token in text.split(";"):
        parts = token.split(",")
        if len(parts) != 2:
            raise ValueError(f"Invalid ROI token: {token}")
        out.append((int(float(parts[0])), int(float(parts[1]))))
    if len(out) < 3:
        raise ValueError("ROI needs at least 3 points")
    return out
